export const TASKS = [
  { id: 1, category: "Work", name: "Finish project report" },
  { id: 2, category: "Work", name: "Email client" },
  { id: 3, category: "Work", name: "Prepare presentation" },
  { id: 4, category: "Work", name: "Attend team meeting" },
  { id: 5, category: "Work", name: "Review code" },
  { id: 6, category: "Family", name: "Buy groceries" },
  { id: 7, category: "Family", name: "Call parents" },
  { id: 8, category: "Family", name: "Plan family trip" },
  { id: 9, category: "Family", name: "Help kids with homework" },
  { id: 10, category: "Family", name: "Schedule doctor appointment" },
  { id: 11, category: "Personal", name: "Exercise" },
  { id: 12, category: "Personal", name: "Read a book" },
  { id: 13, category: "Personal", name: "Meditate" },
  { id: 14, category: "Personal", name: "Journal" },
  { id: 15, category: "Personal", name: "Organize closet" },
  { id: 16, category: "Hobby Ideas", name: "Paint a landscape" },
  { id: 17, category: "Hobby Ideas", name: "Learn guitar" },
  { id: 18, category: "Hobby Ideas", name: "Write a short story" },
  { id: 19, category: "Hobby Ideas", name: "Build a model airplane" },
  { id: 20, category: "Hobby Ideas", name: "Try a new recipe" }
];
